# Exercício da Aula - Numpy (Prática em Python)

In [1]:
# importando biblioteca e declarando alias
import numpy as np

In [2]:
# cria uma matriz unidimensional
mt = np.array([12, 24, 36, 48])
print(mt)
print(type(mt))

[12 24 36 48]
<class 'numpy.ndarray'>


In [3]:
# criar o array com um tipo específico
# cria o array como um float de 64 bits
mtfloat = np.array([2, 4, 6, 8, 10], dtype = np.float64)
print(mtfloat)
print(type(mtfloat))
# cria o array como um inteiro de 32 bits
mtint = np.array([2, 4, 6, 8, 10], dtype = np.int32)
print(mtint)
print(type(mtint))

[ 2.  4.  6.  8. 10.]
<class 'numpy.ndarray'>
[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [4]:
# mudar o tipo do array
# é possível transformar tipos de dados do array
mtnew = np.array([1.5, 2.0, -33.333333, 4.123124, 5.777])
print(mtnew)
mtnewint = mtnew.astype(np.int32)
print(mtnewint)

[  1.5        2.       -33.333333   4.123124   5.777   ]
[  1   2 -33   4   5]


In [5]:
# também é possível fazer o inverso
mt5 = np.array([1, 2, 3])
print(mt5)
mt6 = mt5.astype(np.float64)
print(mt6)

[1 2 3]
[1. 2. 3.]


In [6]:
# cria matriz com mais de uma dimensão
# bidimensional
mt7 = np.array([[10, 20, 30], [40, 80, 120], [160, 320, 480]])
print(mt7)

[[ 10  20  30]
 [ 40  80 120]
 [160 320 480]]


In [7]:
# cria arrays vazios tipificados
# empty significa que não são inicializados, não que são vazios
vazio = np.empty([3,2], dtype = int)
print(vazio)
print("----------")
# cria uma matriz nula
zeros = np.zeros([4,3])
print(zeros)
print("----------")
# cria uma matriz composta por valores um
one = np.ones([4,3])
print(one)
print("----------")
# cria uma matriz quadrada com diagonal principal com valores 1 e outros valores 0
square_mt = np.eye(5)
print(square_mt)

[[35833632        0]
 [       0        0]
 [       0        0]]
----------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
# cria valores aleatórios entre 0 e 1
random_num = np.random.random((5))
print(random_num)
print("----------")
# valores aleatórios (distribuição normal) contendo negativos
random_negative = np.random.randn((5))
print(random_negative)
print("----------")
# valores aleatórios matriz 3 x 4
random_mt = np.array(10 * np.random.random((3,4)))
print(random_mt)

[0.30401874 0.25670027 0.19126319 0.05987148 0.11639156]
----------
[ 1.14756733 -0.92561294  1.47258526 -0.71639481 -1.55946256]
----------
[[3.80649807 1.7816336  8.06614384 3.54237514]
 [8.28264765 8.24270872 2.65651781 0.51042839]
 [1.40863026 4.34161383 6.45872757 2.76303203]]


In [12]:
# usando seeds para geração de aleatórios
seed = np.random.default_rng(1)
random_seed = seed.random(5)
print(random_seed)
print("----------")
# gerar inteiros
random_int = seed.integers(10, size=(3,4))
print(random_int)

[0.51182162 0.9504637  0.14415961 0.94864945 0.31183145]
----------
[[8 4 2 8]
 [2 4 6 5]
 [0 0 8 7]]


In [13]:
# unique remove repetições
j = np.array([10, 11, 13, 15, 12, 20, 11, 14, 10, 15, 24, 12.4])
j = np.unique(j)
print(j)

[10.  11.  12.  12.4 13.  14.  15.  20.  24. ]


In [14]:
# funções específicas
# cria a matriz bidimensional k
k = np.array([[5, 10, 15], [10, 20, 30], [15, 30, 45]])
print(k)
print("----------")
# acessando elemento
print(k[0,1])
print("----------")
# mostra as dimensões
print(k.shape)

[[ 5 10 15]
 [10 20 30]
 [15 30 45]]
----------
10
----------
(3, 3)


In [15]:
# Funções matemáticas
# valor máximo
print(k.max())
# valor mínimo
print(k.min())
# soma dos valores
print(k.sum())
# média dos valores
print(k.mean())
# desvio padrão dos valores (standard deviation)
print(k.std())

45
5
180
20.0
12.01850425154663


In [18]:
# funções universais aplicadas a todos os elementos
# raiz quadrada
k1 = np.array([1, 2, 9, 16, 36, 64])
print(np.sqrt(k1))
# valor exponencial
print(np.exp(k1))

[1.         1.41421356 3.         4.         6.         8.        ]
[2.71828183e+00 7.38905610e+00 8.10308393e+03 8.88611052e+06
 4.31123155e+15 6.23514908e+27]


In [19]:
# extração de elementos
m = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
# mostra elemento específico
print(m[1])
print("----------")
# mostra o array criado a partir da posição zero, dois elementos
print(m[0:2])
print("----------")
# mostra o array criado a partir da 2° posição até o final
print(m[1:])
print("----------")
# mostra o array criado a partir da antepenúltima posição até o final
print(m[-3:])

2
----------
[1 2]
----------
[2 3 4 5 6 7 8 9]
----------
[7 8 9]


In [20]:
# extração de linhas e colunas
l = np.array([[4, 5], [6, 1], [7, 3]])
print(l)
print("----------")
# primeira linha, todas as colunas
print(l[0,:])
print("----------")
# segunda linha, todas as colunas
print(l[1,:])
print("----------")
# terceira linha, todas as colunas
print(l[2,:])
print("----------")
# primeira coluna, todas as linhas
print(l[:,0])
print("----------")
# segunda coluna, todas as linhas
print(l[:,1])

[[4 5]
 [6 1]
 [7 3]]
----------
[4 5]
----------
[6 1]
----------
[7 3]
----------
[4 6 7]
----------
[5 1 3]


In [23]:
# adição e multiplicação de matrizes
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n + o
print(res1)
print("----------")
res2 = n * o
print(res2)
print("----------")
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([2, 1])
print(p + q)

[[2 3]
 [4 5]]
----------
[[1 2]
 [3 4]]
----------
[[3 3]
 [5 5]
 [7 7]]


In [25]:
# transposição, rearranja um conjunto de 15 elementos de 0 a 14
# em 3 linhas e 5 colunas
f = np.arange(15).reshape((3, 5))
# mostra a matriz transposta
print(f)
print("----------")
s = f.T
"""
or: s = f.transpose((1,0))

A ordem das dimensões é especificada com a tupla (1,0), indicando que a segunda dimensão -
(as colunas) deve vir primeiro e a primeira dimensão (as linhas) deve vir em seguida.
"""
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
----------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [26]:
# expressões lógicas com where
# criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
print("-------------------------")
# criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
print("-------------------------")
# criando matriz com valores 1 e -1 baseado nos valores do array x
z = np.where(x > 0, 1, -1)
print(z)

[[-0.01613584 -1.59836593  0.86558429 -0.84140193]
 [-0.87819836  0.28338729  1.24447659 -1.0563189 ]
 [-0.03100878 -0.41319769  0.89741604 -1.07566358]
 [-0.19762208  0.20017659 -0.24028604 -0.74392869]]
-------------------------
[[False False  True False]
 [False  True  True False]
 [False False  True False]
 [False  True False False]]
-------------------------
[[-1 -1  1 -1]
 [-1  1  1 -1]
 [-1 -1  1 -1]
 [-1  1 -1 -1]]
